/**
 * Semantic embeddings for Obsidian notes using Rust + Candle
 *
 * Provides fast, local embedding generation for semantic search without external API calls.
 */

// The .node file is generated by napi-rs build
// eslint-disable-next-line @typescript-eslint/no-var-requires
const native = require('./semantic-embeddings.node');

export const SemanticEmbeddings = native.SemanticEmbeddings;

// Re-export types (these will be auto-generated by napi-rs)
export type { SemanticEmbeddings } from './index.d';
